core/urls.py
from django.urls import path

from core import views

app_name = "core"

urlpatterns = [
    ### GRANTGOAL URLS ###
    path('list/grantgoal/', views.ListGrantGoal.as_view(), name="list_grantgoal"),
    path('detail/grantgoal/<int:pk>/', views.DetailGrantGoal.as_view(), name="detail_grantgoal"),
    path('create/grantgoal/', views.CreateGrantGoal.as_view(), name='create_grantgoal'),
]

dplaest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
]

examen2/nfl_project/nfl/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('equipos/', views.lista_equipos, name='lista_equipos'),
    path('ciudades/', views.lista_ciudades, name='lista_ciudades'),
    path('', views.home, name='home'),
]

examen2/nfl_project/nfl_project/urls.py
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('nfl/', include('nfl.urls')),
]

home/urls.py
from django.urls import path




from home import views


app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
]

core/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import timedelta

# Create your models here.

STATE_CHOICES = (
    ('Done', 'DN' ),
    ('Doing', 'DG'),
    ('Not Stared', 'NS'),
)


class GrantGoal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    grantgoal_name = models.CharField(max_length=64, default="Generic Grant Goal")
    description = models.CharField(max_length=256, default="Generic Grant Goal Description")
    timestamp = models.DateField(auto_now_add=True)
    final_date = models.DateField(auto_now_add=False, blank=True, null=True)
    update_date = models.DateField(auto_now=True)
    days_duration = models.IntegerField(default=7)
    status = models.BooleanField(default=True)
    state = models.CharField(max_length=16, choices=STATE_CHOICES)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.grantgoal_name

@receiver(post_save, sender=GrantGoal)
def end_time_grantgoal(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
        instance.save()

# @receiver(post_save, sender=GrantGoal)
# def end_time_grantgoal(sender, instance, **kwargs):
#     if instance.final_date is None or instance.final_date=='':
#         instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
#         instance.save()

examen2/nfl_project/nfl/models.py
from django.db import models

class Ciudad(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Equipo(models.Model):
    nombre = models.CharField(max_length=100)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.CASCADE)
    estadio = models.ForeignKey('Estadio', on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class Estadio(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

home/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms

from .models import GrantGoal

class GrantGoalForm(forms.ModelForm):
    class Meta:
        model = GrantGoal
        fields = [
            "user",
            "grantgoal_name",
            "description",
            "days_duration",
            "state",
            "status",
            "slug"
        ]
        widgets = {
            "user": forms.Select(attrs={"class": "form-select", "type":"select"}),
            "grantgoal_name": forms.TextInput(attrs={"type": "text", "class":"form-control", "placeholder":"Escribe el nombre del grantgoal"}),
            "description": forms.Textarea(attrs={"type": "text", "class":"form-control", "placeholder":"Escribe la descripcion del grantgoal", "rows":3}),
            "days_duration": forms.NumberInput(attrs={"type": "number", "class":"form-control", "placeholder":"Escribe el numero de dias de duracion del grantgoal"}),
            "state": forms.Select(attrs={"type": "select", "class": "form-select"})
        }

core/views.py
from django.shortcuts import render

from django.views import generic
from django.urls import reverse_lazy

from .models import GrantGoal
from .forms import GrantGoalForm

# Create your views here.


# # # #   G R A N T G O A L  C R U D  # # # # # 

## CREATE GRANT GOAL
class CreateGrantGoal(generic.CreateView):
    template_name = "core/create.html"
    model = GrantGoal
    form_class = GrantGoalForm
    success_url = reverse_lazy('core:list_grantgoal')

## RETRIEVE GRANT GOAL
# LIST GRANT GOAL
class ListGrantGoal(generic.ListView):
    template_name = "core/list.html"
    model = GrantGoal #queryset = GrantGoal.objects.filter(status=True)

# DETAIL GRANT GOAL
class DetailGrantGoal(generic.View):
    template_name = "core/detail.html"
    context = {}

    def get(self, request, pk):
        grantgoal = GrantGoal.objects.get(id=pk)
        self.context = {
            "grantgoal": grantgoal
        }
        return render(request, self.template_name, self.context)


## UPDATE GRANT GOAL

## DELETE GRANT GOAL

examen2/nfl_project/nfl/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Ciudad, Equipo

def home(request):
    return render(request, 'home.html')
def lista_equipos(request):
    equipos = Equipo.objects.all()
    return render(request, 'nfl/lista_equipos.html', {'equipos': equipos})

def lista_ciudades(request):
    ciudades = Ciudad.objects.all()
    return render(request, 'nfl/lista_ciudades.html', {'ciudades': ciudades})

home/views.py
from django.shortcuts import render
from django.views import generic
# Create your views here.


class Index(generic.View):
    template_name = "home/index.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "Ray Parra"
        }
        return render(request, self.template_name, self.context)

examen2/nfl_project/nfl/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tu Sitio Web</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Inicio</a>
        <!-- Puedes agregar más elementos de navegación aquí -->
    </nav>
    <div class="container mt-5">
        {% block content %}{% endblock %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

examen2/nfl_project/nfl/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>Bienvenido a Mi Sitio</h1>
<p>Este es el contenido de la página de inicio. Puedes personalizarlo como desees.</p>

{% endblock %}

examen2/nfl_project/nfl/templates/lista_ciudades.html
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Ciudades</title>
</head>
<body>
    <h1>Lista de Ciudades con Equipos</h1>
    <ul>
        {% for ciudad in ciudades %}
            <li>{{ ciudad.nombre }}</li>
        {% empty %}
            <li>No hay ciudades disponibles con equipos.</li>
        {% endfor %}
    </ul>
</body>
</html>

examen2/nfl_project/nfl/templates/lista_equipos.html
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Equipos</title>
</head>
<body>
    <h1>Lista de Equipos</h1>
    <ul>
        {% for equipo in equipos %}
            <li>{{ equipo.nombre }}</li>
        {% empty %}
            <li>No hay equipos disponibles.</li>
        {% endfor %}
    </ul>
</body>
</html>

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <!-- NAV BAR -->
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="#">Navbar</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Dropdown
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="#">Action</a></li>
                              <li><a class="dropdown-item" href="#">Another action</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                          </li>
                        </ul>
                        <form class="d-flex" role="search">
                          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                          <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                      </div>
                    </div>
                  </nav>
                <!-- END NAV BAR -->
            </div>
        </div>
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                {% block content %}
                  
                {% endblock content %}
            </div>
            <div class="col-2"></div>
        </div>
        <div class="row">
            <div class="col">
                <footer class="text-center text-white" style="background-color: #f1f1f1;">
                    <!-- Grid container -->
                    <div class="container pt-4">
                      <!-- Section: Social media -->
                      <section class="mb-4">
                        <!-- Facebook -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-facebook-f"></i
                        ></a>
                  
                        <!-- Twitter -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-twitter"></i
                        ></a>

                        <i class="glyphicon glyphicon-cloud"></i>

                  
                        <!-- Google -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-google"></i
                        ></a>
                  
                        <!-- Instagram -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-instagram"></i
                        ></a>
                  
                        <!-- Linkedin -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-linkedin"></i
                        ></a>
                        <!-- Github -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-github"></i
                        ></a>
                      </section>
                      <!-- Section: Social media -->
                    </div>
                    <!-- Grid container -->
                  
                    <!-- Copyright -->
                    <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                      © 2020 Copyright:
                      <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
                    </div>
                    <!-- Copyright -->
                  </footer>
            </div>
        </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/core/create.html
{% extends "base/base.html" %}

{% block title %}
  CREATE GRANT GOAL VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-outline-success form-control">Create</button>
            <a href="{% url 'core:list_grantgoal' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/core/detail.html
{% extends "base/base.html" %}

{% block title %}
  DETAIL GRANT GOAL VIEW
{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ grantgoal.grantgoal_name }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the {{grantgoal.grantgoal_name}} Grant Goal .</strong> {{grantgoal.description}}
        </div>
        
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Date Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the Duration {{ grantgoal.days_duration}} days for the grantgoal item's.</strong> It is timestamp {{ grantgoal.timestamp}} grantgoal.
          <br>
          The Final Date for the grantgoal is: {{ grantgoal.final_date }}
          <br>
          The status for the grantgoal is: {{ grantgoal.status }}
          <br>
          <a href="{% url 'core:list_grantgoal'%}">back to list</a> 
        </div>
      </div>
    </div>
  </div>
  
{% endblock content %}

templates/core/list.html
{% extends "base/base.html" %}

{% block title %}
  LIST GRANT GOAL VIEW
{% endblock title %}

{% block content %}
    <table class="table table-hover">
        <thead>
            <th>ID</th>
            <th>GG NAME</th>
            <th>TIMESTAMP</th>
            <th>FINAL DATE</th>
            <th>STATUS</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for gg in object_list %}
                <tr>
                    <td>{{ gg.id }}</td>
                    <td>{{ gg.grantgoal_name }}</td>
                    <td>{{ gg.timestamp }}</td>
                    <td>{{ gg.final_date }}</td>
                    <td>{{ gg.status }}</td>
                    <td><a href="{% url 'core:detail_grantgoal' gg.id %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/home/index.html
{% extends 'base/base.html' %}

{% block title %}IndexViews{% endblock title %}

{% block content %}
    <h1>Hola {{ name }} Bienvenido a los Chismes! ... XD</h1>
{% endblock content %}

 